# Site settings
title: Meeting Notes for the Kansas City Brigade
email: pbarham@codeforamerica.org
description: > # this means to ignore newlines until "baseurl:"
    Kansas City Brigade for Code for Amarica Meeting notes
baseurl: "/meeting-notes" # the subpath of your site, e.g. /blog/
url: "http://codeforkansascity.github.io/meeting-notes" # the base hostname & protocol for your site
twitter_username: codeforkc
github_username:  codeforkansascity

# Build settings
markdown: kramdown
